version: '3'
services: # each service run simultaneously (parallel)

  backend:
    image: backend:latest
    depends_on:
      - frontend
    restart: always
    ports:
      - 8080:8080
  
  frontend:
    image: frontend:latest
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true