version: '3'
services: # each service run simultaneously (parallel)

  server:
    build:
      context: .
      dockerfile: ./Back/post/Dockerfile
    depends_on:
      - frontend
    restart: always
    ports:
      - 8080:8080
    env_file:
      - ~/aws_env_creds
    networks:
      - host


  frontend:
    build:
      context: .
      dockerfile: ./Front/tryReact/my-app/Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - host