version: '3'
services: # each service run simultaneously (parallel)

  server:
    build: .
    image: backend:latest
    depends_on:
      - frontend
    restart: always
    ports:
      - 8080:8080
    env_file:
      - ~/aws_env_creds
    networks:
      - adoptme


  frontend:
    image: frontend:latest
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - adoptme

networks:
  adoptme: